// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: email_verification.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
  member_id, 
  token
) VALUES (
  $1, $2
)
RETURNING id, member_id, token, is_used, created_at, updated_at
`

type CreateEmailVerificationParams struct {
	MemberID uuid.UUID `json:"member_id"`
	Token    string    `json:"token"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (EmailVerification, error) {
	row := q.db.QueryRow(ctx, createEmailVerification, arg.MemberID, arg.Token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Token,
		&i.IsUsed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
